// Code generated by "stringer -type=ForeignKeyOption"; DO NOT EDIT.

package index

import "fmt"

const _ForeignKeyOption_name = "ForeignKeyDeleteRestrictForeignKeyDeleteCascadeForeignKeyDeleteSetNullForeignKeyDeleteSetDefaultForeignKeyDeleteNoActionForeignKeyUpdateRestrictForeignKeyUpdateCascadeForeignKeyUpdateSetNullForeignKeyUpdateSetDefaultForeignKeyUpdateNoActionNone"

var _ForeignKeyOption_index = [...]uint8{0, 24, 47, 70, 96, 120, 144, 167, 190, 216, 240, 244}

func (i ForeignKeyOption) String() string {
	if i < 0 || i >= ForeignKeyOption(len(_ForeignKeyOption_index)-1) {
		return fmt.Sprintf("ForeignKeyOption(%d)", i)
	}
	return _ForeignKeyOption_name[_ForeignKeyOption_index[i]:_ForeignKeyOption_index[i+1]]
}
