-- generated by github.com/mackee/go-genddl. DO NOT EDIT!!!

DROP TABLE IF EXISTS `location`;

CREATE TABLE `location` (
    `id` BIGINT unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(191) COLLATE utf8mb4_general_ci NOT NULL,
    `description` VARCHAR(191) COLLATE utf8mb4_general_ci NOT NULL,
    `place` GEOMETRY NOT NULL SRID 4326,
    SPATIAL KEY place (`place`),
    FULLTEXT KEY description (`description`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


DROP TABLE IF EXISTS `product`;

CREATE TABLE `product` (
    `id` INTEGER unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(191) COLLATE utf8mb4_general_ci NOT NULL,
    `type` INTEGER unsigned NOT NULL,
    `user_id` INTEGER unsigned NOT NULL,
    `received_user_id` INTEGER unsigned NULL,
    `description` TEXT COLLATE utf8mb4_general_ci NOT NULL,
    `full_description` MEDIUMTEXT COLLATE utf8mb4_general_ci NOT NULL,
    `size` INTEGER NULL,
    `status` TINYINT unsigned NOT NULL,
    `category` TINYINT NOT NULL,
    `created_at` DATETIME(6) NOT NULL,
    `updated_at` DATETIME(6) NULL,
    `removed_at` DATETIME(6) NULL,
    UNIQUE user_id_type (`user_id`, `type`),
    INDEX user_id_created_at (`user_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;


DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
    `id` INTEGER unsigned NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `name` VARCHAR(255) COLLATE utf8mb4_general_ci NOT NULL UNIQUE,
    `age` BIGINT NULL,
    `message` VARCHAR(191) COLLATE utf8mb4_general_ci NULL,
    `icon_image` BLOB NOT NULL,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE VIEW `user_product`
  (`u_id`, `u_name`, `ru_name`, `p_id`, `p_type`) AS
  SELECT u.id, u.name, ru.name, p.id, p.type FROM product AS p
    INNER JOIN user AS u ON p.user_id = u.id
    LEFT JOIN user AS ru ON p.received_user_id = ru.id;

CREATE VIEW `user_product_structured`
  (`p_id`, `p_name`, `p_type`, `p_user_id`, `p_received_user_id`, `p_description`, `p_full_description`, `p_size`, `p_status`, `p_category`, `p_created_at`, `p_updated_at`, `p_removed_at`, `u_id`, `u_name`, `u_age`, `u_message`, `u_icon_image`, `u_created_at`, `u_updated_at`, `ru_id`, `ru_name`, `ru_age`, `ru_message`, `ru_icon_image`, `ru_created_at`, `ru_updated_at`) AS
  SELECT p.*, u.*, ru.* FROM product AS p
    INNER JOIN user AS u ON p.user_id = u.id
    LEFT JOIN user AS ru ON p.received_user_id = ru.id;

ALTER TABLE `product` ADD CONSTRAINT `fk_product_user_id` FOREIGN KEY user_id (`user_id`) REFERENCES `user`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
