-- generated by github.com/mackee/go-genddl. DO NOT EDIT!!!

DROP TABLE IF EXISTS "location";

CREATE TABLE "location" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "place" GEOMETRY NOT NULL,
    SPATIAL KEY place ("place"),
    FULLTEXT KEY description ("description")
) ;


DROP TABLE IF EXISTS "product";

CREATE TABLE "product" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "type" INTEGER NOT NULL,
    "user_id" INTEGER NOT NULL,
    "received_user_id" INTEGER NULL,
    "description" TEXT NOT NULL,
    "size" INTEGER NULL,
    "created_at" DATETIME NOT NULL,
    "updated_at" DATETIME NULL,
    UNIQUE ("user_id", "type"),
    FOREIGN KEY ("user_id") REFERENCES user("id") ON DELETE CASCADE ON UPDATE CASCADE
) ;
CREATE INDEX product_user_id_created_at ON product ("user_id", "created_at");


DROP TABLE IF EXISTS "user";

CREATE TABLE "user" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL UNIQUE,
    "age" INTEGER NULL,
    "message" TEXT NULL,
    "icon_image" BLOB NOT NULL,
    "created_at" DATETIME NOT NULL,
    "updated_at" DATETIME NULL
) ;

CREATE VIEW "user_product" AS
  SELECT p.id, u.name, ru.name, p.id, p.type FROM product AS p
    INNER JOIN user AS u ON p.user_id = u.id
    LEFT JOIN user AS ru ON p.received_user_id = ru.id;

